spring:
  cloud:
    gateway:
      routes[0]:
        id: spgl
        uri: lb://SPGL
        predicates[0]: Path=/spgl/**
    loadbalancer:
      ribbon:
        enabled: 'false'
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}