spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://mysql-docker-container/spgl?allowPublicKeyRetrieval=true&useSSL=false
    #url: jdbc:mysql://localhost/spgl?allowPublicKeyRetrieval=true&useSSL=false
    username: '{cipher}e3b08e820b924110be0a0eda0008196ec9c08eea379df3684aeaf285186ad343'
    password: '{cipher}e3b08e820b924110be0a0eda0008196ec9c08eea379df3684aeaf285186ad343'
    hikari:
      poolName: pool

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/api-gateway-security
          #issuer-uri: http://localhost:9090/realms/api-gateway-security

server:
  port: "8081"

app:
  context: /spgl
  async:
    withDLQRetry: true
    retryDelay: 1000
    maxRetries: 1
    prefetchCount : 10000
    flux:
      maxConcurrency: 500
    global:
      autoDeleteOnIdle: 7200

#Basic Authentication
#constant:
#  user: '{cipher}1bf2dd3ff0ca051571d28e1576787325b68b3089326a3fa514b01004ea1887d5'
# password: '{cipher}1bf2dd3ff0ca051571d28e1576787325b68b3089326a3fa514b01004ea1887d5'

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
      #defaultZone: http://localhost:8761/eureka